from cozmo_fsm import *
from yoloDetect import *
import time
import numpy as np
import cv2
c = 0
img_cache = np.zeros([240,320,3])
cache_turn = 0
class GetTurn(StateNode):
    def __init__(self):
        super().__init__()
        
    def start(self, event=None):
        super().start(event)
        turn = 0
        turn = detect(img_cache)
        turn *= -0.5
        self.post_data(cozmo.util.Angle(turn))
class GetCurve(StateNode):
    def __init__(self):
        super().__init__()
        
    def start(self, event=None):
        speed = 35
        diff = 20
        super().start(event)
        turn = cache_turn
        if turn > 2:
            print("cozmo idle while waiting for target")
            self.post_data([-8,-8])
            return
        left = turn * diff + speed
        right = -turn * diff + speed
        self.post_data([left, right])

class followV2(StateMachineProgram):
    # setup{
    #     start: ClearCache() =TM=> query: Query("Is cube2 sideways?") 
    #     =TM=> Query("ow many cubes are there?")
    # =TM=> Query("What is the distance between cube1 and cube2?")
    # =TM=> Query("Which cube is closest to cube1?")
    # =TM=> Query("Please remember that all cubes are 45 mm on a side.") 
    # =TM=> Query("How big is cube1?") 
    # =TM=> Query("What is the volume of cube3?") 
    
    # }
    def user_image(self,image,gray):
        self.robot.myimage = gray
        
        global c
        global img_cache
        global cache_turn
        
        c += 1
        if c == 1:
            c = 0
            img_cache = image
            t0 = time.time()
            cache_turn = detect(img_cache)
            print("inference took ", time.time() - t0, "seconds")

    
    # setup{
    #     ColorImageEnabled() =C=> getTurn: GetTurn() =D=> DriveWheel =C=> getTurn
    # }
    def setup(self):
        #         ColorImageEnabled() =C=> getCurve: GetCurve() =D=> DriveWheels(6,6) =T(0.6)=> getCurve
        
        # Code generated by genfsm on Fri Apr 26 15:26:58 2024:
        
        colorimageenabled1 = ColorImageEnabled() .set_name("colorimageenabled1") .set_parent(self)
        getCurve = GetCurve() .set_name("getCurve") .set_parent(self)
        drivewheels1 = DriveWheels(6,6) .set_name("drivewheels1") .set_parent(self)
        
        completiontrans1 = CompletionTrans() .set_name("completiontrans1")
        completiontrans1 .add_sources(colorimageenabled1) .add_destinations(getCurve)
        
        datatrans1 = DataTrans() .set_name("datatrans1")
        datatrans1 .add_sources(getCurve) .add_destinations(drivewheels1)
        
        timertrans1 = TimerTrans(0.6) .set_name("timertrans1")
        timertrans1 .add_sources(drivewheels1) .add_destinations(getCurve)
        
        return self
